### ISSUE TITLE
마트휴일 > 롯데마트 > 경기 > 판교점 선택시 오류

### ISSUE THREAD

**Issue by AndersonChoi** [hongsii/mart-holiday-alarm#26]
![image](https://user-images.githubusercontent.com/9148605/62357260-a52fe700-b54d-11e9-854a-01e6ca0f9494.png)
롯데마트 판교점 선택시 첨부파일과 같이 오류가 발생합니다.

**Comment by hongsii** [comment]
@AndersonChoi 이슈 확인이 많이 늦었습니다. 죄송합니다 ㅠㅠㅠ

롯데마트는 이름이 같은 마트가 2개씩 존재하는 경우가 있어 중복된 마트를 플친에서 조회하게 되면 문제가 발생하고 있습니다. 해당 버그는 최대한 빠른 시일 내에 수정하겠습니다.
제보해주셔서 감사합니다 :)
